-- =====================================================
-- 1. Create schemas
-- =====================================================
create schema if not exists core;
create schema if not exists rail;

-- =====================================================
-- 2. Dataset registry
-- =====================================================
create table if not exists core.dataset (
    dataset_id      bigint generated by default as identity primary key,
    dataset_name    text not null,
    dataset_type    text not null,
    source_uri      text,
    source_format   text,
    source_crs      text,
    target_srid     integer not null,
    version_tag     text,
    ingested_at     timestamptz not null default now(),
    notes           text
);

-- =====================================================
-- 3. Rail corridor
-- =====================================================
create table if not exists rail.corridor (
    corridor_id     bigint generated by default as identity primary key,
    corridor_code   text not null unique,
    corridor_name   text not null,
    description     text
);

-- =====================================================
-- 4. Generic GIS asset table
-- =====================================================
create table if not exists rail.gis_asset (
    gis_asset_id        bigint generated by default as identity primary key,
    corridor_id         bigint not null references rail.corridor(corridor_id) on delete cascade,
    asset_type          text not null,
    asset_subtype       text,
    asset_name          text,
    asset_code          text,
    status              text,
    source_dataset_id   bigint references core.dataset(dataset_id) on delete set null,
    properties          jsonb,
    geom                geometry(Geometry, 2154) not null
);

create index if not exists gis_asset_geom_gix
on rail.gis_asset
using gist (geom);

create index if not exists gis_asset_corridor_idx
on rail.gis_asset (corridor_id);

create index if not exists gis_asset_source_dataset_idx
on rail.gis_asset (source_dataset_id);
